name: rescale_simmon_lnx Build
run-name: ${{ github.actor }} is building Rescale Simulation Monitor
on:
  workflow_dispatch:
    inputs:
      share:
        description: 'Share job with HPC'
        required: false
env:
  ANALYSIS_CODE: rescale_simmon_lnx
  RESCALE_API_KEY: ${{ secrets.RESCALE_API_KEY }}
jobs:
  BUILD-RESCALE_SIMMON_LNX:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run build
        run: |
          cd .build
          source build.sh ${{ env.ANALYSIS_CODE }} $(date +"%Y.%m.%d") ${{ inputs.share }}