name: rescale_simmon_lnx Build
run-name: ${{ github.actor }} is building Rescale Simulation Monitor
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be deployed'
        required: true
      jira:
        description: 'Create JIRA HPC task'
        required: true
        default: false
        type: boolean
env:
  ANALYSIS_CODE: rescale_simmon_lnx
jobs:
  BUILD-RESCALE_SIMMON_LNX:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check out IBT PILErepository code
        uses: actions/checkout@v4
        with:
          repository: rescale/soln-ibt-pipelines
          path: ibt_tools
      - name: Run build
        run: |
          tree
